### ISSUE TITLE
minor sonarqube issues

### ISSUE THREAD

**Issue by neutmute** [richardszalay/pshosts#16]
Thanks for making this code available. I copy and pasted it into my own .net core solution and it works great.

I just ran SonarQube across my code base and it had some complaints about the `HostEntry.cs`

![hosts](https://user-images.githubusercontent.com/1303131/33535378-5306a1be-d901-11e7-8843-3e5d1231e24a.png)

**Comment by richardszalay** [comment]
Thanks, merged!
