### ISSUE TITLE
Add IPAddress property to HostEntry

### ISSUE THREAD

**Issue by richardszalay** [richardszalay/pshosts#2]
`HostEntry.Address` returns a string, which makes sense as it may not be a valid IP address and is also the "primary key" in many respects. However, it would be useful for there to be an IPAddress property that has a value when `Address` _is_ a valid IP as it would would allow things like `$_.IPAddress.IsLoopback()`.

**Comment by joandrsn** [comment]
`IsLoopback()` is a static method. So if you want to use `IsLoopback()` you would have to write `[IPAddress]::IsLoopback($_.IPAddress)`.

**Comment by richardszalay** [comment]
Good point, which would indeed be quite awkward in terms of syntax.

Do you think having a typed property adds any value?

**Comment by joandrsn** [comment]
I only use this cmdlet for fast enabling/disabling of many host rules at once. I could see some usage in being able to only select which ones are actually loopbacks.

You could add your own IPAddress class which could have that as a property.
But I'm not sure if that's going to far.

**Comment by richardszalay** [comment]
I guess I could also add a `IsLoopback` convenience property to the host entry object. That way you could easy disable all local loopback entries using `Get-HostEntry | ?{ $_.IsLoopback} | Disable-HostEntry`

**Comment by joandrsn** [comment]
I have created a pull request. Unfortunately I couldn't test if it actually worked since my visual studio couldn't find the `System.Management.Automation`.
Could you test it?

**Comment by richardszalay** [comment]
Hi @joandrsn, I actually ended up implementing this myself as part of a larger look at convenience parameters / properties for loopback addresses.

I do appreciate you taking the time to PR, though, and I am terribly sorry it took me so long to respond.

Btw, I've now moved `System.Management.Automation` to a NuGet reference so it should be easier to build now.

**Comment by richardszalay** [comment]
(The changes aren't released in the PowerShell Gallery yet, but you can see them in the master branch if you're interested)
